
services: 
  app1:
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
      - payment-processor
    container_name: app1
    hostname: app1
    expose: 
      - "8080"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: 150M

  app2:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app2
    networks:
      - backend
      - payment-processor
    hostname: app2
    expose: 
      - "8080"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: 150m

  nginx:
    image: nginx:alpine
    container_name: nginx
    networks:
      - backend
    ports:
      - "9999:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: 50m

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true